"""add abandoned_at to quiz_sessions

Revision ID: 328c5d48c055
Revises: f5d9d1b19520
Create Date: 2026-07-14 20:22:24.890024

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "328c5d48c055"
down_revision: str | None = "f5d9d1b19520"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz_sessions", sa.Column("abandoned_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quiz_sessions", "abandoned_at")
    # ### end Alembic commands ###
