"""add friendships duels and usernames

Revision ID: dd3684553307
Revises: 328c5d48c055
Create Date: 2026-08-12 15:52:03.946618

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "dd3684553307"
down_revision: str | None = "328c5d48c055"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Alembic does not autogenerate enum value additions.
    op.execute("ALTER TYPE quiz_mode ADD VALUE IF NOT EXISTS 'duel'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friendships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("addressee_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "accepted", "blocked", name="friendship_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["addressee_id"],
            ["users.id"],
            name=op.f("fk_friendships_addressee_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
            name=op.f("fk_friendships_requester_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_friendships")),
        sa.UniqueConstraint(
            "requester_id", "addressee_id", name=op.f("uq_friendships_requester_id")
        ),
    )
    op.create_index(
        "ix_friendships_addressee_status", "friendships", ["addressee_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_friendships_requester_id"), "friendships", ["requester_id"], unique=False
    )
    op.create_table(
        "duels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.Enum("random", "friend", name="duel_mode"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "active", "finished", "expired", name="duel_status"),
            nullable=False,
        ),
        sa.Column("challenger_id", sa.Uuid(), nullable=False),
        sa.Column("challenger_session_id", sa.Uuid(), nullable=False),
        sa.Column("opponent_id", sa.Uuid(), nullable=True),
        sa.Column("opponent_session_id", sa.Uuid(), nullable=True),
        sa.Column("winner_id", sa.Uuid(), nullable=True),
        sa.Column("is_draw", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["challenger_id"],
            ["users.id"],
            name=op.f("fk_duels_challenger_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["challenger_session_id"],
            ["quiz_sessions.id"],
            name=op.f("fk_duels_challenger_session_id_quiz_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opponent_id"],
            ["users.id"],
            name=op.f("fk_duels_opponent_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opponent_session_id"],
            ["quiz_sessions.id"],
            name=op.f("fk_duels_opponent_session_id_quiz_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"], ["users.id"], name=op.f("fk_duels_winner_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_duels")),
    )
    op.create_index("ix_duels_challenger", "duels", ["challenger_id"], unique=False)
    op.create_index("ix_duels_opponent", "duels", ["opponent_id"], unique=False)
    op.create_index("ix_duels_status_mode", "duels", ["status", "mode"], unique=False)
    # Existing rows need a value for these counters.
    for column in (
        "duel_wins",
        "duel_losses",
        "duel_draws",
        "current_duel_streak",
        "best_duel_streak",
    ):
        op.add_column(
            "user_stats", sa.Column(column, sa.Integer(), nullable=False, server_default="0")
        )
        op.alter_column("user_stats", column, server_default=None)

    # username is unique and required: add it nullable, backfill from the email
    # local-part (deduplicated with a numeric suffix), then enforce the constraint.
    op.add_column("users", sa.Column("username", sa.String(length=20), nullable=True))
    op.execute(
        """
        UPDATE users AS u
        SET username = s.base || CASE WHEN s.rn = 1 THEN '' ELSE s.rn::text END
        FROM (
            SELECT id,
                   base,
                   row_number() OVER (PARTITION BY base ORDER BY created_at, id) AS rn
            FROM (
                SELECT id,
                       created_at,
                       COALESCE(
                           NULLIF(
                               left(
                                   regexp_replace(lower(split_part(email, '@', 1)), '[^a-z0-9_]', '', 'g'),
                                   16
                               ),
                               ''
                           ),
                           'mavva'
                       ) AS base
                FROM users
            ) AS cleaned
        ) AS s
        WHERE u.id = s.id
        """
    )
    op.alter_column("users", "username", nullable=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_column("users", "username")
    op.drop_column("user_stats", "best_duel_streak")
    op.drop_column("user_stats", "current_duel_streak")
    op.drop_column("user_stats", "duel_draws")
    op.drop_column("user_stats", "duel_losses")
    op.drop_column("user_stats", "duel_wins")
    op.drop_index("ix_duels_status_mode", table_name="duels")
    op.drop_index("ix_duels_opponent", table_name="duels")
    op.drop_index("ix_duels_challenger", table_name="duels")
    op.drop_table("duels")
    op.drop_index(op.f("ix_friendships_requester_id"), table_name="friendships")
    op.drop_index("ix_friendships_addressee_status", table_name="friendships")
    op.drop_table("friendships")

    # drop_table leaves the enum types behind; remove them so upgrade re-runs clean.
    # ('duel' stays in quiz_mode — Postgres cannot drop a single enum value.)
    bind = op.get_bind()
    for enum_name in ("friendship_status", "duel_mode", "duel_status"):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
