import type { Icon, IconWeight } from '@phosphor-icons/react'
import {
  Acorn,
  ArrowsClockwise,
  Bird,
  BookOpen,
  BookOpenText,
  Bread,
  Campfire,
  ChartLineUp,
  CheckCircle,
  Church,
  Columns,
  Compass,
  Confetti,
  Cross,
  Crown,
  DiceFive,
  EnvelopeSimple,
  Flag,
  Flame,
  Folders,
  Footprints,
  GraduationCap,
  Grains,
  HandsPraying,
  Handshake,
  Hourglass,
  House,
  Info,
  Lightning,
  List,
  LockSimple,
  MagnifyingGlass,
  MapTrifold,
  Medal,
  Megaphone,
  Mountains,
  PencilSimple,
  Plant,
  Prohibit,
  Scroll,
  Shield,
  SignOut,
  SmileySad,
  Sparkle,
  Stairs,
  Star,
  SunHorizon,
  Sword,
  Tent,
  Timer,
  Translate,
  Tree,
  TreeEvergreen,
  Trophy,
  User,
  Users,
  UsersThree,
  Warning,
  Waves,
  XCircle,
} from '@phosphor-icons/react'

export type { Icon }

export function Glyph({
  as: Icon,
  className = 'h-5 w-5',
  weight = 'duotone',
}: {
  as: Icon
  className?: string
  weight?: IconWeight
}) {
  return <Icon weight={weight} className={className} aria-hidden />
}

export const AppIcons = {
  home: House,
  study: BookOpenText,
  duels: Sword,
  review: ArrowsClockwise,
  friends: Handshake,
  ranking: Trophy,
  achievements: Medal,
  suggest: PencilSimple,
  profile: User,
  more: List,
  logout: SignOut,
  streak: Flame,
  streakOff: Campfire,
  manna: Grains,
  plant: Plant,
  star: Star,
  sparkle: Sparkle,
  confetti: Confetti,
  timer: Timer,
  chart: ChartLineUp,
  users: Users,
  search: MagnifyingGlass,
  lock: LockSimple,
  mail: EnvelopeSimple,
  pray: HandsPraying,
  warning: Warning,
  flag: Flag,
  sad: SmileySad,
  check: CheckCircle,
  miss: XCircle,
  sun: SunHorizon,
  hourglass: Hourglass,
  prohibit: Prohibit,
  levelUp: TreeEvergreen,
  crown: Crown,
  dice: DiceFive,
  scroll: Scroll,
  cross: Cross,
  info: Info,
} as const

const CATEGORY_BY_SLUG: Record<string, Icon> = {
  personagens: User,
  'livros-da-biblia': BookOpen,
  'geografia-biblica': MapTrifold,
  reis: Crown,
  profetas: Megaphone,
  evangelhos: Cross,
  cartas: EnvelopeSimple,
  milagres: Waves,
  parabolas: Plant,
  doutrinas: Columns,
  escatologia: Bird,
  'historia-de-israel': Scroll,
  'historia-da-igreja': Church,
  'cronologia-biblica': Hourglass,
  'organizacao-da-biblia': Folders,
  'eventos-biblicos': Lightning,
  'teologia-biblica': BookOpenText,
  'contexto-historico': Columns,
  'costumes-judaicos': Scroll,
  genealogias: Tree,
  'festas-judaicas': Confetti,
  'idiomas-biblicos': Translate,
  'cultura-biblica': Acorn,
}

const CATEGORY_BY_EMOJI: Record<string, Icon> = {
  '👤': User,
  '📚': BookOpen,
  '🗺️': MapTrifold,
  '👑': Crown,
  '📣': Megaphone,
  '✝️': Cross,
  '✉️': EnvelopeSimple,
  '🌊': Waves,
  '🌱': Plant,
  '🏛️': Columns,
  '🕊️': Bird,
  '🇮🇱': Scroll,
  '⛪': Church,
  '⏳': Hourglass,
  '🗂️': Folders,
  '⚡': Lightning,
  '📖': BookOpenText,
  '🏺': Columns,
  '🕎': Scroll,
  '🌳': Tree,
  '🎺': Confetti,
  '🔤': Translate,
  '🫒': Acorn,
}

export function CategoryGlyph({
  slug,
  emoji,
  className = 'h-6 w-6',
}: {
  slug?: string
  emoji?: string
  className?: string
}) {
  const Icon =
    (slug && CATEGORY_BY_SLUG[slug]) || (emoji && CATEGORY_BY_EMOJI[emoji]) || BookOpenText
  return <Glyph as={Icon} className={className} />
}

const ACHIEVEMENT_ICONS: Record<string, Icon> = {
  streak_3: Flame,
  streak_7: Tent,
  streak_30: Shield,
  streak_100: Sparkle,
  correct_10: Footprints,
  correct_50: PencilSimple,
  correct_250: Scroll,
  correct_1000: GraduationCap,
  answered_100: Stairs,
  answered_500: Mountains,
  perfect_1: Star,
  perfect_10: Sparkle,
  level_5: Plant,
  level_10: Tree,
  xp_1000: Bread,
  xp_5000: Grains,
  categories_all: Compass,
  duel_win_1: Sword,
  duel_win_10: Sword,
  duel_win_50: Shield,
  duel_streak_3: Handshake,
  duel_streak_10: Crown,
  duel_played_25: Trophy,
  duel_flawless_1: Star,
  duel_flawless_5: Sparkle,
}

export function AchievementGlyph({
  code,
  className = 'h-8 w-8',
}: {
  code: string
  className?: string
}) {
  return <Glyph as={ACHIEVEMENT_ICONS[code] ?? Medal} className={className} />
}

export {
  ArrowsClockwise,
  BookOpenText,
  Campfire,
  ChartLineUp,
  CheckCircle,
  Confetti,
  Cross,
  Crown,
  DiceFive,
  EnvelopeSimple,
  Flame,
  Grains,
  HandsPraying,
  Handshake,
  House,
  Hourglass,
  List,
  LockSimple,
  Prohibit,
  MagnifyingGlass,
  Medal,
  PencilSimple,
  Plant,
  Scroll,
  SignOut,
  SmileySad,
  Sparkle,
  Star,
  SunHorizon,
  Sword,
  Timer,
  TreeEvergreen,
  Trophy,
  User,
  Users,
  UsersThree,
  Warning,
  XCircle,
}
